version: 2

defaults: &defaults
  working_directory: ~/project/vux-demo
  docker:
    - image: circleci/node:latest

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-vue-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - v1-vue-{{ .Branch }}-
            - v1-vue-
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: v1-vue-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - node_modules/
      - persist_to_workspace:
          root: ~/project
          paths:
            - vux-demo

  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      # - run: npm run lint

  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run: npm run build

workflows:
  version: 2
  install-and-parallel-test:
    jobs:
      - install
      - build:
          requires:
            - install
      - lint:
          requires:
            - install